redmine_people/config/routes.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2019 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
  collection do
    get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
    post :bulk_edit, :bulk_update, :send_mails, :add_manager
    delete :bulk_destroy
    get 'calendar' => 'people_calendars#index'
    resources :holidays, except: :show, controller: :people_holidays, as: :people_holidays
  end

  member do
    get :manager
    get :autocomplete_for_manager
    delete :destroy_avatar
    get 'tabs/:tab' => 'people#show', :as => 'tabs'
    get 'load_tab' => 'people#load_tab', :as => 'load_tab'
    delete 'remove_subordinate' => 'people#remove_subordinate', :as => 'remove_subordinate'
  end
  resources :people_rates, except: [:index, :show]
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
    get 'tabs/:tab' => 'departments#show', :as => 'tabs'
    get 'load_tab' => 'departments#load_tab', :as => 'load_tab'
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

redmine_people/app/controllers/people_calendars_controller.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2019 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class PeopleCalendarsController < ApplicationController
  unloadable

  include PeopleHolidaysHelper
  include PeopleCalendarsHelper
  helper :queries
  include QueriesHelper
  helper :sort
  include SortHelper

  def index
    raise Unauthorized unless User.current.allowed_people_to?(:view_people)

    if params[:year] && params[:year].to_i > 1900
      @year = params[:year].to_i
      if params[:month] && params[:month].to_i > 0 && params[:month].to_i < 13
        @month = params[:month].to_i
      end
    end
    @year ||= User.current.today.year
    @month ||= User.current.today.month

    @calendar = Redmine::Helpers::Calendar.new(Date.civil(@year, @month, 1), current_language, :month)

    retrieve_people_holidays_query
    @query.group_by = nil
    if @query.valid?
      events = []
      events += @query.holidays(:conditions => ['((start_date BETWEEN ? AND ?) OR (end_date BETWEEN ? AND ?))', @calendar.startdt, @calendar.enddt, @calendar.startdt, @calendar.enddt])
      events += @query.birthdays(:month => @calendar.month) if show_birthdays?

      @calendar.custom_events = events
    end
  end
end

redmine_people/app/helpers/people_calendars_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2019 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module PeopleCalendarsHelper
  include CalendarsHelper
  include PeopleHelper

  def show_birthdays?
    params[:birthdays].present? || (params[:birthdays].blank? && params[:set_birthdays].blank?)
  end

  def render_person_tooltip(person, options={})
    emails = person.mail.split(/,/).map{|email| "<span class=\"email\" style=\"white-space: nowrap;\">#{mail_to email.strip}</span>"}.join(', ')
    phones = person.phone.split(/,/).map{|phone| "<span class=\"phone\" style=\"white-space: nowrap;\">#{phone.strip}</span>"}.join(', ')

    s = link_to(person.name, person_path(person), options) + "<br /><br />".html_safe
    s <<  "<strong>#{l(:label_people_job_title)}</strong>: #{person.job_title}<br />".html_safe unless person.job_title.blank?
    s <<  "<strong>#{l(:field_mail)}</strong>: #{emails}<br />".html_safe unless person.mail.blank?
    s <<  "<strong>#{l(:label_people_phone)}</strong>: #{phones}<br />".html_safe unless person.phone.blank?
    s
  end
end

redmine_people/app/views/people_calendars/_calendar.html.erb
<table class="cal">
  <thead>
  <tr><th scope="col" title="<%= l(:label_week) %>" class="week-number"></th><% 7.times do |i| %><th scope="col"><%= day_name( (calendar.first_wday+i)%7 ) %></th><% end %></tr>
  </thead>
  <tbody>
  <tr>
    <% day = calendar.startdt
       while day <= calendar.enddt %>
        <%= ("<td class='week-number' title='#{ l(:label_week) }'>#{(day+(11-day.cwday)%7).cweek}</td>".html_safe) if day.cwday == calendar.first_wday %>
        <td class="<%= day.month==calendar.month ? 'even' : 'odd' %><%= ' today' if User.current.today == day %><%= ' holiday' if calendar.holiday?(day) && day.month==calendar.month %><%= ' weekend' if calendar.holiday?(day) && calendar.weekend?(day) && day.month==calendar.month %>">
          <p class="day-num"><%= day.day %></p>
            <% calendar.events_on(day).each do |i| %>
                <% if i.is_a? PeopleHoliday %>
                  <%# unless calendar.weekend?(day) %>
                    <div class="<%= 'starting' if day == i.start_date %> <%= 'ending' if day == i.due_date %> tooltip">
                      <span class="icon no-icon"></span>
                      <%= i.name %>
                      <% if i.description.present? %>
                          <span class="tip"><%= i.description %></span>
                      <% end %>
                    </div>
                  <%# end %>
                <% elsif i.is_a? PeopleInformation %>
                    <div class="birthday tooltip">
                      <span class="icon icon-cake"></span>
                      <%= link_to i.person.name, person_path(i.person) %>
                      <span class="tip"><%= render_person_tooltip(i.person) %></span>
                    </div>
                <% end %>
            <% end %>
        </td>
        <%= '</tr><tr>'.html_safe if day.cwday==calendar.last_wday and day!=calendar.enddt %>
        <% day = day + 1
       end %>
  </tr>
  </tbody>
</table>

redmine_people/app/views/people_calendars/index.html.erb
<div class="contextual">
  <%= link_to l(:label_people_holiday_new), new_people_holiday_path, :class => 'icon icon-add' if User.current.allowed_people_to?(:manage_calendar) %>
</div>
<h2><%= l(:label_calendar) %></h2>

<%= form_tag({:controller => 'people_calendars', :action => 'index'},
             :method => :get, :id => 'query_form') do %>
    <%= hidden_field_tag 'set_filter', '1' %>
    <%= hidden_field_tag 'set_birthdays', params[:birthdays].blank? ? '1' : '0' %>

    <fieldset id="options" class="collapsible collapsed">
      <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
      <div style="display: none;">
        <table>
          <tr>
            <td><label class="inline"><%= check_box_tag :birthdays, 1, show_birthdays? %><%= l(:label_people_birthdays) %></label></td>
          </tr>
        </table>
      </div>
    </fieldset>

    <p style="float:right;">
      <%= link_to_previous_month(@year, @month, :accesskey => accesskey(:previous)) %> | <%= link_to_next_month(@year, @month, :accesskey => accesskey(:next)) %>
    </p>

    <p class="buttons">
      <%= label_tag('month', l(:label_month)) %>
      <%= select_month(@month, :prefix => "month", :discard_type => true) %>
      <%= label_tag('year', l(:label_year)) %>
      <%= select_year(@year, :prefix => "year", :discard_type => true) %>

      <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
      <%= link_to l(:button_clear), { :project_id => @project, :set_filter => 1 }, :class => 'icon icon-reload' %>
    </p>
<% end %>

<%= error_messages_for 'query' %>

<%= render :partial => 'calendar', :locals => {:calendar => @calendar} %>

<%= call_hook(:view_calendars_show_bottom, :year => @year, :month => @month, :project => @project, :query => @query) %>

<% content_for :sidebar do %>
    <%= render :partial => 'people/sidebar' %>
<% end %>

<% html_title(l(:label_calendar)) -%>