redmine_questions/config/routes.rb
# This file is a part of Redmine Q&A (redmine_questions) plugin,
# Q&A plugin for Redmine
#
# Copyright (C) 2011-2019 RedmineUP
# http://www.redmineup.com/
#
# redmine_questions is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_questions is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_questions.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# match '/news/:id/comments', :to => 'comments#create', :via => :post
# match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete
resources :questions do
  collection do
    put :preview
    put :update_form
    # match :preview, :to => 'questions#preview', :via => [:get, :put, :post]
    get :autocomplete_for_subject
    get :topics
    get :index_public
  end
  member do
    get :from_issue
    # post :new_comment
  end
  resources :questions_answers, :as => :answers
end

resources :questions_answers, :except => [:show, :index] do
  collection do
    put :preview
  end
end

match "questions_votes", :to => 'questions_votes#create', :via => [:get, :post], :as => 'questions_votes'

resources :questions_comments do
  member do
    post :update
  end
end

resources :questions_sections
resources :questions_statuses, :except => :show

resources :projects do
  resources :questions_sections
  resources :questions
end

match "projects/:project_id/questions/questions_sections/:section_id" => "questions#index", :via => [:get]
match "questions/questions_sections/:section_id" => "questions#index", :via => [:get]
match 'auto_completes/questions_tags' => 'auto_completes#questions_tags', :via => :get, :as => 'auto_complete_questions_tags'

redmine_questions/app/views/projects/_questions_settings.html.erb
<% @project_sections = QuestionsSection.for_project(@project).sorted %>
<h3><%= l(:label_questions_sections_plural) %></h3>

<% if @project_sections.any? %>
  <table class="list questions_sections">
    <thead>
      <tr>
      <th><%= l(:field_name) %></th>
      <th><%=l(:field_type)%></th>
      <th></th>
      </tr>
    </thead>
    <tbody>
      <% @project_sections.each do |section| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td class="name">
            <%= h(section.name) %>
          </td>
          <td>
            <%= section.l_type %>
          </td>
          <td class="buttons">
            <% if User.current.allowed_to?(:manage_sections, @project) %>
              <%= reorder_handle(section, url: project_questions_section_path(@project, section), param: 'questions_section') if respond_to?(:reorder_handle) %>
              <%= link_to l(:button_edit), edit_questions_section_path(section, project_id: @project), class: 'icon icon-edit' %>
              <%= delete_link questions_section_path(section, project_id: @project) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% if User.current.allowed_to?(:manage_sections, @project) %>
  <%= link_to image_tag('add.png', style: 'vertical-align: middle;') + l(:label_questions_section_new), new_questions_section_path(project_id: @project) %>
<% end %>

<%= javascript_tag do %>
  $(function() { $("table.questions_sections tbody").positionedItems(); });
<% end if respond_to?(:reorder_handle) %>